<?php
 $_cat = new Mage_Catalog_Block_Navigation();
 $curent_cat = $_cat->getCurrentCategory();
 $curent_cat_id = $curent_cat->getId(); 
 $category = Mage::registry('current_category')->getName(); 
$_cat = new Mage_Catalog_Block_Navigation();
$curent_cat = $_cat->getCurrentCategory();
$curent_cat_id = $curent_cat->getId(); 
 $category = Mage::registry('current_category')->getName(); 
 $products = Mage::getModel('catalog/category')->load($curent_cat_id)
    ->getProductCollection()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('status', 1)
    ->addAttributeToFilter('visibility', 4);
?>

<div id="venexamlist">
    <h1><?php echo $category;?> Exams</h1>
   <ul>
        <?php $i = 0; foreach($products as $_product):?>
            <li><a href="<?php echo $_product->getProductUrl()?>"><?php echo $_product->getSku();?></a></li>
        <?php if ($i++ > 20) break; endforeach;?>
   </ul>
    <div class="foot"></div>
</div>