<style>
.New_Release_text a, .hotexam-t a {color:#29517A;}
</style>
<?php 

 $categoryId = 2;

 $category = Mage::getModel('catalog/category')->load($categoryId);

 $resource = Mage::getSingleton('core/resource');

	$read = $resource->getConnection('catalog_read');

	$categoryProductTable = $resource->getTableName('catalog/category_product');

	$categoryTable = $resource->getTableName('catalog_category_entity');

	$productEntityIntTable = (string)Mage::getConfig()->getTablePrefix() . 'catalog_product_entity_int';

	$eavAttributeTable = $resource->getTableName('eav/attribute');

	$select_subcat = $read->select()

						  ->from(array('cat'=>$categoryTable))

						  ->where('cat.path LIKE ?',$category->getPath().'/%')

						  ;

	$subcategories = $read->fetchAll($select_subcat);

	$subcatids = array();

	if(!empty($subcategories)):

		foreach( $subcategories as $subcategory ):

		$subcatids[] = $subcategory['entity_id'];

		endforeach;

	endif;

	array_push($subcatids,$categoryId);

				   

	$select = $read->select()

				   ->from(array('cp'=>$categoryProductTable))

				   ->join(array('pei'=>$productEntityIntTable), 'pei.entity_id=cp.product_id', array())

				   ->joinNatural(array('ea'=>$eavAttributeTable))

				   ->where('cp.category_id IN(?)', $subcatids)

				   ->where('pei.value=1')

				   ->where('ea.attribute_code="new_release"');



				   $rows = $read->fetchAll($select);

	$ids = array();



	foreach($rows AS $row) {

	  $ids[] = $row['product_id'];

	}

	$ret = implode(",", $ids);

	$collection = Mage::getModel('catalog/product')->getCollection();

  $collection->getSelect()->where("e.entity_id in (?)", $ids);

  $collection->addAttributeToSelect(array('name','price','url_key','small_image'));

  $collection->setOrder('entity_id','desc');

  $productList = $collection->load();

  $count_hotproduct = count($productList);

?>



<?php  if($count_hotproduct){ ?>

<div class="New_Release">

<div class="code_layout">

<div class="roundcorner_1"></div>

<div class="roundcorner_2"></div>

</div>

	<div class="code_title_left">

        <h3>New Release</h3>

    </div>

    <div class="code_title_right">

        <a href="">

             <img src="/skin/frontend/default/default/images/btn_go.gif"/>

        </a>

    </div>

    <div class="New_Release_text">

	  <ul id="NewRelease">

     

      <?php $i=0;?>

	  	<?php foreach( $productList as $product_new_release):?>

         <?php $i++;?>

	      <li data-id="<?php echo $product_new_release->getId();?>">

			  <a href="<?php echo $product_new_release->getProductUrl();?>" >

				<?php echo $product_new_release->getSku();?>

			  </a>

		  </li>

          <?php if($i>=22){break;}?>

	 	<?php endforeach;?>

	  </ul>

   </div>

</div>	  

<?php  } ?>

	




