<style type="text/css">
#venexamlist {
	background: #e9eff5;
	width: 253px;
	height: 220px;
}
#venexamlist h1 {
	background: #d9e3ee;
	color: #ff6600;
	text-align: left;
}
#venexamlist ul {
	padding: 0 10px;
}
#venexamlist ul li {
	width: 72px;
	float: left;
	padding: 5px 0 5px 5px;
	margin: 0;
	overflow: hidden;
}
.list-right {
	margin-top: 170px;
	width: 255px;
}
#topCent {
	width: 980px;
	padding: 0 10px;
}
.bigPad {
	width: 445px;
}
</style>

<div id="venexamlist">
  <h1>Hot Exams</h1>
  <?php
		$categories_ids = array(370,272,163);
		
		$formId_cats = array();
		foreach($categories_ids as $get_id){
			$formId_cats[] =  Mage::getModel('catalog/category')->load($get_id);
		}
		
		
		foreach ($formId_cats as $category) {
		
			if ($category->getIsActive()) {

	 $categoryId = $category->getId();
	 $category = Mage::getModel('catalog/category')->load($categoryId);
	 $resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('catalog_read');
		$categoryProductTable = $resource->getTableName('catalog/category_product');
		$categoryTable = $resource->getTableName('catalog_category_entity');
		$productEntityIntTable = (string)Mage::getConfig()->getTablePrefix() . 'catalog_product_entity_int';
		$eavAttributeTable = $resource->getTableName('eav/attribute');
		$select_subcat = $read->select()
		                      ->from(array('cat'=>$categoryTable))
							  ->where('cat.path LIKE ?',$category->getPath().'/%')
							  ;
		$subcategories = $read->fetchAll($select_subcat);
		$subcatids = array();
		if(!empty($subcategories)):
			foreach( $subcategories as $subcategory ):
			$subcatids[] = $subcategory['entity_id'];
			endforeach;
		endif;
		array_push($subcatids,$categoryId);
					   
		$select = $read->select()
					   ->from(array('cp'=>$categoryProductTable))
					   ->join(array('pei'=>$productEntityIntTable), 'pei.entity_id=cp.product_id', array())
					   ->joinNatural(array('ea'=>$eavAttributeTable))
					   ->where('cp.category_id IN(?)', $subcatids)
					   ->where('pei.value=1')
					   ->where('ea.attribute_code="hot_product"');

					   $rows = $read->fetchAll($select);
		$ids = array();

		foreach($rows AS $row) {
		  $ids[] = $row['product_id'];
		}
		$ret = implode(",", $ids);
		$collection = Mage::getModel('catalog/product')->getCollection();
	  $collection->getSelect()->where("e.entity_id in (?)", $ids);
	  $collection->addAttributeToSelect(array('name','sku','url_key'));
	  $collection->setOrder('SKU','asc');
	  $productList = $collection->load();
	  $count_hotproduct = count($productList);
	  
	  if($count_hotproduct){
	  echo '<ul>';
	  	$i = 0;
	  	foreach( $productList as $product_hot):
	      echo '<li><a class="popo_a" href="'.trim($product_hot->getSku()).'.html">'.$product_hot->getSku().'</a></li>';
		if ($i++ > 4) break;
	 	endforeach;
	  echo '</ul>';
	  }
	}
}
?>
  <!--div class="foot"></div--> 
</div>